---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-CentOS.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3
  notify: restart docker

- name: Install python-pip
  package:
    name: python-pip
    state: present
    version: latest
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

#- name: Self-upgrade Pip.
#  pip:
#    name:
#      - pip
#    state: latest
#  register: pkg_res
#  until: ( pkg_res is success )
#  retries: 3

- name: Install docker from pip.
  pip:
    name:
      - docker
    state: present
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
