---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-CentOS.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  register: pkg_res
  retries: 3
  until: pkg_res | success
  notify: restart docker

- name: Install python-pip
  package:
    name: python-pip
    state: present
  register: pkg_res
  retries: 3
  until: pkg_res | success

- name: Self-upgrade Pip.
  pip:
    name:
      - pip
#    state: latest
  extra_args: --upgrade
  register: pip_res
  retries: 3
  until: pip_res | success

- name: Install docker from pip.
  pip:
    name:
      - docker
    state: present
  register: pip_res
  retries: 3
  until: pip_res | success

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
