---

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-CentOS.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Install python-pip
  package:
    name: python-pip
    state: present

- name: Self-upgrade Pip.
  pip:
    name: 
      - pip
    state: latest

- name: Install docker from pip.
  pip:
    name:
      - docker
#      - docker-py
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
  
