---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-CentOS.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3
#  notify: restart docker

- name: Install python-pip
  package:
    name: python-pip
    state: present
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

- name: Check current pip version.
  command: pip --version
  register: pip_current_version
  changed_when: false
  failed_when: false

- name: Upgrade pip if it's different
  pip:
    name:
      - pip
    state: latest
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3
  when: >
      pip_current_version.stdout is defined
      and pip_version not in pip_current_version.stdout

- name: Install docker from pip.
  pip:
    name:
      - docker
    state: present
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
