---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
#      - docker-ce
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Updates apt cache
  apt: update_cache=true
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
  register: pkg_res
  until: ( pkg_res is success )
  retries: 3

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: apt_key_res
  until: ( apt_key_res is success )
  retries: 3
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -"
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
